version: "3.8"

services:
  forest-db:
    container_name: forest-db
    image: mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      forest-net:

  forest-app:
    container_name: forest-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - forest-db
    networks:
      forest-net:
    restart: on-failure

networks:
  forest-net:

volumes:
  db_data:
